version: '3'
services:

  mysql:
    image: mysql:latest
    restart: on-failure
    volumes:
      - $HOME/Documents/hashkart:/data/db
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306